[package]
name = "bevyray"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14"
bevy-inspector-egui = "0.25"
bevy_mod_picking = "0.20"
bevy_transform_gizmo = "0.12"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
