[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C",
    "link-arg=-fuse-ld=lld",
    # Nightly only
    "-Zshare-generics=y",
    "-Zthreads=0",
]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = [
    # Nightly only
    "-Zshare-generics=y",
    "-Zthreads=0",
]
